# Generated by Django 4.2.17 on 2025-02-08 21:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Heeler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bssid", models.CharField(max_length=32)),
                ("ssid", models.CharField(max_length=32)),
                ("frequency_mhz", models.IntegerField(default=-1)),
                ("time_stamp_z", models.DateTimeField()),
            ],
            options={
                "ordering": ("ssid",),
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active_flag", models.BooleanField(default=False)),
                ("location", models.CharField(max_length=32)),
                ("host", models.CharField(max_length=32)),
                ("latitude_decdeg", models.FloatField(default=0.0)),
                ("longitude_decdeg", models.FloatField(default=0.0)),
                ("type", models.CharField(max_length=32)),
            ],
            options={
                "ordering": ("host",),
            },
        ),
        migrations.CreateModel(
            name="Hyena",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flight", models.CharField(max_length=32)),
                ("hex", models.CharField(max_length=32)),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("hex",),
            },
        ),
        migrations.CreateModel(
            name="Poodle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humidity_pct", models.FloatField(default=-1.0)),
                ("temperature_c", models.FloatField(default=-1.0)),
                ("pressure_mb", models.FloatField(default=-1.0)),
                ("orientation_pitch_rads", models.FloatField(default=-1.0)),
                ("orientation_roll_rads", models.FloatField(default=-1.0)),
                ("orientation_yaw_rads", models.FloatField(default=-1.0)),
                ("time_stamp_z", models.DateTimeField()),
            ],
            options={
                "ordering": ("time_stamp_z",),
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("active_flag", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=32)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
