# Generated by Django 4.2.17 on 2025-01-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skunk", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="heeler",
            options={"ordering": ("ssid",)},
        ),
        migrations.RenameField(
            model_name="heeler",
            old_name="address",
            new_name="bssid",
        ),
        migrations.RenameField(
            model_name="heeler",
            old_name="essid",
            new_name="ssid",
        ),
    ]
