# Generated by Django 4.2.17 on 2025-01-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skunk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(max_length=32)),
                ('hex', models.CharField(max_length=32)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('hex',),
            },
        ),
    ]
