# Generated by Django 4.2.17 on 2025-01-10 04:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heeler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('essid', models.CharField(max_length=32)),
                ('frequency', models.CharField(max_length=32)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('essid',),
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_flag', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('type', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('host',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active_flag', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
